DROP TABLE IF EXISTS history CASCADE;
CREATE TABLE history (
  id SERIAL PRIMARY KEY NOT NULL,
  game_type VARCHAR(255) NOT NULL,
  player_1 INTEGER REFERENCES users(id) ON DELETE CASCADE,
  player_2 INTEGER REFERENCES users(id) ON DELETE CASCADE,
  result VARCHAR(255),
  time_played TIMESTAMP NOT NULL
);
